name: Debug Build
on:
  push:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: O que tem nas pastas?
      run: |
        echo "--- Raiz do projeto ---"
        ls -F
        echo "--- Conteudo da pasta app ---"
        ls -R app/ || echo "Pasta app nao encontrada!"

    - name: Log do Gradle
      run: ./gradlew tasks --all || echo "Gradle nao reconheceu o projeto"
